name: covres
description: A application for all Covid Resources

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  velocity_x: ^3.0.0
  webview_flutter: ^2.0.4
  modal_progress_hud: ^0.1.3
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  firebase_analytics: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/